export const GET_RANK_REQUESTED = "GET_RANK_REQUESTED";
export const GET_RANK_SUCCESS = "GET_RANK_SUCCESS";
export const GET_RANK_ERROR = "GET_RANK_ERROR";

export const SET_RANK_REQUESTED = "SET_RANK_REQUESTED";
export const SET_RANK_SUCCESS = "SET_RANK_SUCCESS";
export const SET_RANK_ERROR = "SET_RANK_ERROR";
